// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PraticaMigration.Context;

#nullable disable

namespace PraticaMigration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250827032055_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PraticaMigration.Models.Jogador", b =>
                {
                    b.Property<int>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JogadorId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("int");

                    b.Property<int>("PosicaoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("JogadorId");

                    b.HasIndex("PosicaoId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("PraticaMigration.Models.Posicao", b =>
                {
                    b.Property<int>("PosicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PosicaoId"));

                    b.Property<string>("PosicaoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PosicaoId");

                    b.ToTable("Posicoes");

                    b.HasData(
                        new
                        {
                            PosicaoId = 1,
                            PosicaoNome = "Atacante"
                        },
                        new
                        {
                            PosicaoId = 2,
                            PosicaoNome = "Meia"
                        },
                        new
                        {
                            PosicaoId = 3,
                            PosicaoNome = "Zagueiro"
                        },
                        new
                        {
                            PosicaoId = 4,
                            PosicaoNome = "Goleiro"
                        });
                });

            modelBuilder.Entity("PraticaMigration.Models.Jogador", b =>
                {
                    b.HasOne("PraticaMigration.Models.Posicao", "Posicao")
                        .WithMany("Jogadores")
                        .HasForeignKey("PosicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posicao");
                });

            modelBuilder.Entity("PraticaMigration.Models.Posicao", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
